[package]
name = "smoothing"
version = "0.1.0"
edition = "2021"

[dependencies]
tiktoken-rs = "0.6.0"
anyhow = "1.0.79"
tch = "0.19.0"
rand = "0.9.1"
csv = "1.3.1"
indicatif = "0.17"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
